/**
 * This class is generated by jOOQ
 */
package com.spring.demo.jooq;


import com.spring.demo.jooq.tables.Abc;
import com.spring.demo.jooq.tables.Company;
import com.spring.demo.jooq.tables.Employee;
import com.spring.demo.jooq.tables.Person;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mylocaldb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mylocaldb.abc</code>.
     */
    public static final Abc ABC = com.spring.demo.jooq.tables.Abc.ABC;

    /**
     * The table <code>mylocaldb.company</code>.
     */
    public static final Company COMPANY = com.spring.demo.jooq.tables.Company.COMPANY;

    /**
     * The table <code>mylocaldb.employee</code>.
     */
    public static final Employee EMPLOYEE = com.spring.demo.jooq.tables.Employee.EMPLOYEE;

    /**
     * The table <code>mylocaldb.person</code>.
     */
    public static final Person PERSON = com.spring.demo.jooq.tables.Person.PERSON;
}
